version: 2.0

jobs:
  build:
    parallelism: 3
    working_directory: ~/exchange_resource
    docker:
      - image: circleci/ruby:2.4-node
      - image: mysql:5.7
        environment:
          DATABASE_USERNAME: root
          DATABASE_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout
      - run:
          name: Install mysql-client
          command: sudo apt install -y mysql-client
      - attach_workspace:
          at: ~/exchange_resource
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/exchange_resource/vendor/bundle
      - persist_to_workspace:
          root: .
          paths: vendor/bundle

      #Database setup
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run: |
          bundle exec rspec --profile 10\
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb") | circleci tests spli

      # Save test results for timing anlysis
      - store_test_results:
          path: test_results
